
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.75.0
    hooks:
      - id: terraform_fmt
      - id: terraform_docs
      - id: terraform_docs_replace
      - id: terraform_tflint
      - id: terraform_tfsec
      - id: terraform_checkov
